[build]
  command = "ng build"
  publish = "dist/my-portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "ng serve"
  port = 4200
  targetPort = 4200

[images]
  remote_images = ["https://via.placeholder.com/*"]
